### ISSUE TITLE
i2c detection 

### ISSUE THREAD

**Issue by Marlon2808** [bravemonkey-13/DarkSky_Display#1]
Hi 
First thanks for uploading the Code and second I have got a problem with my i2cdetection. I use an i2c Backpack for my LCD, and I tried to find my address with 2cdetect -y 1 . The table showed that there is one device connected on the address 3f. Is that a problem, because it seems like everybody else on the internet has detected addresses from 20 up to 27, but not 3f.
Do you want ideas how to set it on an address between 20 and 27?

**Comment by bravemonkey-13** [comment]
Sorry for the late reply, I don't check this account often.

You should be able to modify the I2C_LCD_driver.py file with that address - in mine it shows:
#LCD Address
ADDRESS = 0x27

You can change it to 
#LCD Address
ADDRESS = 0x3f

That should fix it; otherwise you could try changing the connection on the raspberry pi - 

I have my LCD SDA going to pin 3 (GPIO 8) and SCL going to pin 5 (GPIO 9) according to the diagram here:
http://pi4j.com/pins/model-3b-rev1.html

**Comment by bravemonkey-13** [comment]
As issue is not related to the DarkSky_Display.py code but the the display configuration I'm going to close this issue.
